name: DisguiseMe
main: falkirks\disguiseme\DisguiseMe
version: 1.1
author: Falkirks
api: [3.0.0-ALPHA5]
load: POSTWORLD
permissions:
 disguiseme:
  default: op
  children:
   disguiseme.disguise:
    default: op
    description: Disguise!
   disguiseme.other:
    default: op
    description: Disguise others
   disguiseme.exempt:
    default: false
    description: See through disguises
