name: DisguiseMe
main: disguiseme\DisguiseMe
version: 1.1
author: Falkirks
api: [1.13.0]
load: POSTWORLD
commands:
 d:
  permission: disguiseme.disguise
  usage: /d <name> [player]
permissions:
 disguiseme:
  default: op
  children:
   disguiseme.disguise:
    default: op
    description: Disguise!
   disguiseme.other:
    default: op
    description: Disguise others
   disguiseme.exempt:
    default: op
    description: See through disguises
